language: csharp
sudo: false

mono:
  - 4.8.0
solution: FSDN.sln

before_install:
- export CXX='g++-4.8'
- nvm install 6.0.0 && nvm use 6.0.0

before_script:
 - chmod +x ./build.sh
script:
  - ./build.sh

cache:
  directories:
    - paket-files
    - packages
    - node_modules
    - database/packages

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
